Repository Compiler-CampusMinden/CB-Vorlesung-Master, pull requests merged in 2023-11, with the labels that each got.

#123 Lecture: add solution to german telephone challenge (lexing)
  lecture/frontend/lexing/src/GerTel.g4
Labels: vorlesungen, w23

#124 Lecture: add solution to canadian telephone challenge (lexing)
  lecture/frontend/lexing/src/CanadTelco.g4
Labels: vorlesungen, w23

#125 Lexing iban
  lecture/frontend/lexing/antlr-lexing.md
  lecture/frontend/lexing/src/Iban.g4
Labels: vorlesungen, w23

#126 fix link to proposed paper for testing talk
  homework/talk.md
Labels: bug, aufgaben, w23, PO23 (CPL)

#133 org: rescheduling after cancelled sessions in week 46
  readme.md
Labels: high prio, vorlesungen, w23

#134 org: add Nelson's visit to Minden Campus
  readme.md
Labels: vorlesungen, w23

#107 org: adapt planning of talks
  homework/project.md
  homework/talk.md
  readme.md
Labels: vorlesungen, w23, PO18 (CB), PO23 (CPL)
