Repository Compiler-CampusMinden/CB-Vorlesung-Master, pull requests merged in 2024-10, with the labels that each got.

#200 Orga: replace homework assignment w/ workshop status meetings
  readme.md
Labels: aufgaben, prüfungen, orga

#202 Orga: rename 'lr' lecture in roadmap
  readme.md
Labels: orga

#192 Homework: rework Project
  homework/project.md
Labels: aufgaben, high prio, prüfungen

#203 Lecture: rework regular language
  lecture/01-lexing/regular.md
Labels: vorlesungen

#204 Lecture: rework CFG
  lecture/02-parsing/cfg.md
Labels: vorlesungen

#205 Lecture: rework LL parsing
  lecture/02-parsing/ll-parser.md
Labels: vorlesungen

#207 Lecture: fix math mode (LL parsing)
  lecture/02-parsing/images/LL-Parser.tex
Labels: vorlesungen

#209 Lecture: fix automaton example (LR)
  lecture/02-parsing/images/Parser-Automat.png
  lecture/02-parsing/images/Parser-Automat.tex
Labels: bug, vorlesungen
